_("Company")
_("Facility")
_("Name")
_("Status")
_("MP state:  <i>{{ object.measurementpointstate.jsondata }}</i><br />")
_("MP control queue status: <i>{{ object.mpointcontrolqueuestatus.jsondata }}</i><br />")
_("MP input queue status: <i>{{ object.mpointinputqueuestatus.jsondata }}</i><br />")
_("MP output queue status: <i>{{ object.mpointoutputqueuestatus.jsondata }}</i>")
_("Measurement point")
_("Data")
_("Description")
_("Time")
_("Attribute")
_("Amount")
_("External id")
_("Conversion factor")
_("Active")
