_("Measurement point")
_("Data")
_("Status")
_("MP state:  <i>{{ object.measurementpointstate.jsondata }}</i><br />")
_("MP control queue status: <i>{{ object.mpointcontrolqueuestatus.jsondata }}</i><br />")
_("MP input queue status: <i>{{ object.mpointinputqueuestatus.jsondata }}</i><br />")
_("MP output queue status: <i>{{ object.mpointoutputqueuestatus.jsondata }}</i>")
_("Measurement point")
_("Data")
_("Description")
_("Time")
_("Attribute")
_("Amount")
_("External id")
_("Conversion factor")
_("Active")
_("Sign in")
_("Wrong login or password, try again")
_("User name")
_("Password")
_("or sign in with")
_("I forgot my password")
_("Register")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("Cancel")
_("OK")
_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Import data to table")
_("Action")
_("Previous operation")
_("Product")
_("Location")
_("RFID")
_("Feature")
_("Last operation")
_("Search results")
_("Search")
_("Change password")
_("Setup")
_("Logout")
_("Login")
_("Company")
_("Facility")
_("Name")
