_("Edit page")
_("Edit page source")
_("This page do not exists yet!")
_("New attachement")
_("Download")
_("Search results")
_("Search")
_("Change password")
_("Manage")
_("Logout")
_("Login")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("Wiki pages")
_("New wiki page")
_("Sign in")
_("Wrong login or password, try again")
_("User name")
_("Password")
_("or sign in with")
_("I forgot my password")
_("Register")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("Cancel")
_("OK")
_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Import data to table")
_("Action")
