_("Edit page")
_("Edit page source")
_("This page do not exists yet!")
_("Wiki pages")
_("New wiki page")
_("Modify or create a wiki object")
_("User defined blocks")
_("Report from publication")
_("Search results")
_("Search")
_("Change password")
_("Setup")
_("Logout")
_("Login")
_("name")
_("description")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("Sign in")
_("Wrong login or password, try again")
_("User name")
_("Password")
_("or sign in with")
_("I forgot my password")
_("Register")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("Cancel")
_("OK")
_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Import data to table")
_("Action")
_("group")
_("permission")
_("New element")
_("Type")
_("Code")
_("Name")
