_("Edit page")
_("Edit page source")
_("This page do not exists yet!")
_("New attachement")
_("Download")
_("Search results")
_("Search")
_("Change password")
_("Manage")
_("Logout")
_("Login")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("Wiki pages")
_("New wiki page")
