_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Action")
_("Cancel")
_("Close")
_("Login")
_("User name")
_("Password")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("OK")
_("Import data to table")
_("New application set")
_("Import")
_("Restart server")
_("Update server from git")
_("Select application!")
_("A Message Box")
_("Applications")
_("Table")
_("Choices")
_("Views")
_("Forms")
_("Menu")
_("Tasks")
_("Consumers")
_("Templates")
_("Custom files")
_("User Models")
_("User View")
_("User Url")
_("User Tasks")
_("User Consumers")
_("Doc")
_("&New view")
_("New form")
_("Table list")
_("New task")
_("Tables")
_("New table")
_("Fields")
_("Search results")
_("Search")
_("Administration")
_("Administraction")
_("Change password")
_("Logout")
_("Object information")
_("Delete object ")
_("Error information")
_("Edit page")
_("Edit page source")
_("(This page do not exists yet!)")
_("Install")
_("Open in toolbar")
_("New application")
_("New project")
_("New choice")
_("Name")
_("Description")
_("Choice list")
_("New item")
_("Table field list")
_("New menu item")
_("New wiki item")
_("Menu item list")
_("New slideshow")
_("Generate")
_("New template")
_("Common Groups")
_("New")
_("Update")
_("Back")
_("New element")
_("New attachement")
_("Download")
_("Modify or create a wiki object")
_("&New consumer")
_("Login providers")
_("Next")
_("{{pos}}")
_("{{pos.1}}")
_("Sign in")
_("(or sign in with):")
_("or sign in with")
_("(Sign in):")
_("Authentication")
_("I forgot my password")
_("Wiki pages")
_("New wiki page")
_("New wiki class")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("New locale")
_("Sync translate messages")
_("Import project")
_("Update report")
_("Duplicate report")
_("Classifier")
_("Account state")
_("Order")
_("Kill task")
_("Setup")
_("Download installer")
_("Date")
_("Operator")
_("Data")
_("(Are you sure you want to accept the document)? <br>")
_("(You accept the status): {{ action_name }}")
_("(Are you sure you want to discard the document)? <br>")
_("(You discard the status): {{ action_name }}")
_("New document register")
_("name")
_("description")
_("Register")
_("Target")
_("Number")
_("Status")
_("Discard status:")
_("Report from publication")
_("New field")
_("lp = os.path.dirname(os.path.abspath(__file__))")
_("rp2 = None")
_("rp = environ['PYTIGON_ROOT_PATH']")
_("rp = os.environ['PYTIGON_ROOT_PATH']")
_("{{table.verbose_name|safe}}")
_("{{table.verbose_name_plural|safe}}")
_("{{table.verbose_name}}")
_("{{table.verbose_name_plural}}")
_("{{gfield.parent.verbose_name}}")
_("{{gfield.parent.verbose_name_plural}}")
_("{{app.module_title}}")
_("{{app.title}}")
_("{{item.name}}")
_("Subject")
_("Wiki name")
_("Manage")
_("Choice action")
_("New url")
_("Icon")
_("Wrong login or password, try again")
_("Category")
_("Elements")
_("Element")
_("Pattern")
_("(Logout)")
_("(Login)")
_("New customer")
_("Customers synchronization")
_("New employee")
_("Import employees")
_("New school class")
_("New teacher")
_("New lerner")
_("New school")
_("New student")
_("Back to status:")
_("Are you sure you want to accept the document")
_("You accept the status")
_("Are you sure you want to discard the document")
_("You discard the status")
_("(Bad Token)")
_("(Change Password)")
_("'Your password is now changed.")
_("Bad Token")
_("Set a password")
_("Password Reset")
_("Notifications")
_("self, parent, title, choices")
_("self")
_("{{field.description}}")
_("(A restart signal has been sent, depending on the configuration, the restart may take from a few seconds to several hours).")
_("(it is not possible to send a signal for restart)")
_("A restart signal has been sent, depending on the configuration, the restart may take from a few seconds to several hours")
_("It is not possible to send a signal for restart")
_("Success")
_("Warning")
_("Channel consumers")
_("Other files")
_("Model extensions")
_("View extensions")
_("Url extensions")
_("Task extensions")
_("Channel consumer extensions")
_("Import from git")
_("Update system projects from git")
_("Make migrations")
_("Make all migrations")
_("Migrate")
_("Create auto user")
_("Compile messages")
_("Qinfo")
_("Send mails")
_("Run")
_("New file")
_("New directory")
_("View")
_("Edit")
_("Rename")
_("Copy")
_("Move")
_("Delete")
_("Help")
_("Parameter type")
_("Parameter subtype")
_("Key")
_("Type")
_("Label")
_("Application")
_("Group")
_("Parent id")
_("Operator id")
_("Url paramaters")
_("Direct to template")
_("Title")
_("Version")
_("Base table")
_("Proxy")
_("Generic")
_("Verbose name")
_("Parameters")
_("Default value")
_("Relation to")
_("Url parameters")
_("Null")
_("Blank")
_("Editable")
_("Unique")
_("View type")
_("Url")
_("Asynchronous")
_("Module")
_("Permission")
_("Published group")
_("File type")
_("Module title")
_("Permissions")
_("Applications list")
_("Connected to")
_("Publish")
