_("Forms")
_("New form")
_("Name")
_("Module")
_("Asynchronous")
_("Table list")
_("Templates")
_("New template")
_("Url")
_("Url paramaters")
_("Direct to template")
_("New project")
_("Import")
_("Import from git")
_("Restart server")
_("Update system projects from git")
_("Title")
_("Version")
_("Icon")
_("Select application!")
_("A Message Box")
_("Applications")
_("Table")
_("Choices")
_("Views")
_("Menu")
_("Tasks")
_("Channel consumers")
_("Other files")
_("Model extensions")
_("View extensions")
_("Url extensions")
_("Task extensions")
_("Channel consumer extensions")
_("Doc")
_("Tables")
_("New table")
_("Base table")
_("Proxy")
_("Generic")
_("Verbose name")
_("Fields")
_("New field")
_("Label")
_("Type")
_("Parameters")
_("Initial")
_("Widget")
_("Required")
_("Table field list")
_("Description")
_("Connected to")
_("Null")
_("Blank")
_("Editable")
_("Unique")
_("&New view")
_("View type")
_("New menu item")
_("New wiki item")
_("Permission")
_("Menu item list")
_("New choice")
_("Choice list")
_("File type")
_("Open in toolbar")
_("New application")
_("Module title")
_("Permissions")
_("Applications list")
_("Consumers")
_("&New consumer")
_("Notifications")
_("Common Groups")
_("New")
_("Update")
_("Import project")
_("Refresh")
_("New wiki class")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("Wiki pages")
_("New wiki page")
_("New item")
_("Value")
_("User name")
_("Email")
_("Serial number")
_("IP")
_("Active")
_("Edit page")
_("Edit page source")
_("(This page do not exists yet!)")
_("New element")
_("New document register")
_("name")
_("description")
_("Account state")
_("Make migrations")
_("Make all migrations")
_("Migrate")
_("Create auto user")
_("Compile messages")
_("Qinfo")
_("Send mails")
_("Tag")
_("Application")
_("New tag")
_("Key")
_("Main parameter")
_("New group")
_("New group2")
_("Change password")
_("Setup")
_("Logout")
_("Login")
_("New file")
_("New directory")
_("View")
_("Edit")
_("Rename")
_("Copy")
_("Move")
_("Delete")
_("Help")
_("Back")
_("Release date")
_("Artist")
_("Genre")
_("Subject")
_("Wiki name")
_("Download installer")
_("Manage")
_("Choice action")
_("Run")
_("Translation")
_("Status")
_("Success")
_(
    "A restart signal has been sent, depending on the configuration, the restart may take from a few seconds to several hours"
)
_("Warning")
_("It is not possible to send a signal for restart")
_("New url")
_("New locale")
_("Sync translate messages")
_("New task")
_("Publish")
_("Published group")
_("Install")
_("{{field.description}}")
_("(Artist)")
_("Sign in")
_("Wrong login or password, try again")
_("Password")
_("or sign in with")
_("I forgot my password")
_("Register")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("Cancel")
_("OK")
_("Field")
_("Delete the item")
_("Import data to table")
_("Action")
_("release_date")
_("artist")
_("genre")
