_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Action")
_("Cancel")
_("Close")
_("Login")
_("User name")
_("Password")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("OK")
_("Import data to table")
_("New application set")
_("Import")
_("Restart server")
_("Update server from git")
_("Select application!")
_("A Message Box")
_("Applications")
_("Table")
_("Choices")
_("Views")
_("Forms")
_("Menu")
_("Tasks")
_("Consumers")
_("Templates")
_("Custom files")
_("User Models")
_("User View")
_("User Url")
_("User Tasks")
_("User Consumers")
_("Doc")
_("&New view")
_("New form")
_("Table list")
_("New task")
_("Tables")
_("New table")
_("Fields")
_("Search results")
_("Search")
_("Administration")
_("Administraction")
_("Change password")
_("Logout")
_("Object information")
_("Delete object ")
_("Error information")
_("Edit page")
_("Edit page source")
_("(This page do not exists yet!)")
_("Install")
