_("New application set")
_("Import")
_("Restart server")
_("Select application!")
_("A Message Box")
_("Applications")
_("Table")
_("Choices")
_("Views")
_("Templates")
_("Menu")
_("Urls")
_("User Models")
_("User View")
_("User Url")
_("Forms")
_("Doc")
_("Tables")
_("New table")
_("Table list")
_("New choice")
_("Name")
_("Description")
_("Choice list")
_("New view")
_("New template")
_("New menu item")
_("New wiki item")
_("Menu item list")
