_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Action")
_("Cancel")
_("Close")
_("OK")
_("Cancel2")
_(" Sławomir Chołaj!")
_("(Refresh)")
_("Login")
_("User name")
_("Password")
_("(Login)")
_("(Login)Y")
_("Logout")
_("Change password")
_("Administration")
_("Administraction")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("New element")
_("Back")
_("Import data to table")
_("Get row")
_("New row")
_("Object information")
_("Delete object ")
_("Error information")
_("search")
_("Search results")
_("Search")
