_("New element")
_("Type")
_("Code")
_("Name")
_("New document register")
_("name")
_("description")
_("Document type")
_("Description")
_("Correction")
_("Wiki pages")
_("New wiki page")
_("Type 1")
_("Type 2")
_("Classifier 1")
_("Classifier 2")
_("Classifier 3")
_("New status")
_("Order")
