_("New file")
_("New directory")
_("View")
_("Edit")
_("Rename")
_("Copy")
_("Move")
_("Delete")
_("Setup")
_("Help")
_("Wiki pages")
_("New wiki page")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("IHTML_1 = """")
_("New wiki class")
_("Edit page")
_("Edit page source")
_("This page do not exists yet!")
_("Change password")
_("Logout")
_("Login")
_("Modify or create a wiki object")
_("User defined blocks")
