# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import schlib.schdjangoext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SChApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('module_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Module title')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('perms', models.BooleanField(default=False, verbose_name='Perms')),
                ('index', models.CharField(blank=True, max_length=255, null=True, verbose_name='Index')),
                ('model_code', models.TextField(blank=True, editable=False, null=True, verbose_name='Model code')),
                ('view_code', models.TextField(blank=True, editable=False, null=True, verbose_name='View code')),
                ('urls_code', models.TextField(blank=True, editable=False, null=True, verbose_name='Urls code')),
                ('tasks_code', models.TextField(blank=True, null=True, verbose_name='Tasks code')),
                ('doc', models.TextField(blank=True, editable=False, null=True, verbose_name='Doc')),
                ('user_param', models.TextField(blank=True, null=True, verbose_name='Urser parameter')),
            ],
            options={
                'verbose_name_plural': 'SChApp',
                'verbose_name': 'SChApp',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChAppMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
                ('url_type', models.CharField(blank=True, choices=[('Default', '-'), ('shtml', 'shtml'), ('panel', 'panel')], default='-', max_length=16, null=True, verbose_name='Url type')),
                ('perms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Perms')),
                ('icon', models.CharField(max_length=255, verbose_name='Icon')),
                ('icon_size', models.CharField(choices=[('0', 'small'), ('1', 'medium'), ('2', 'large')], default='1', max_length=1, verbose_name='Icon size')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChApp', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'SChAppMenu',
                'verbose_name': 'SChAppMenu',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChAppSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('ext_apps', models.CharField(blank=True, max_length=255, null=True, verbose_name='Extern applications')),
                ('plugins', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plugins')),
                ('gui_type', models.CharField(choices=[('standard', 'standard'), ('modern', 'modern'), ('tree', 'tree'), ('tray', 'tray'), ('dialog', 'dialog'), ('one_form', 'one_form')], max_length=32, verbose_name='Gui type')),
                ('gui_elements', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gui elements')),
                ('is_hybrid', models.BooleanField(default=False, verbose_name='Is hybrid')),
                ('start_page', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start page')),
                ('user_app_template', models.TextField(blank=True, editable=False, null=True, verbose_name='User application template')),
                ('doc', models.TextField(blank=True, editable=False, null=True, verbose_name='Doc')),
                ('desktop_gui_type', models.CharField(choices=[('auto', 'auto'), ('desktop_standard', 'desktop_standard'), ('desktop_modern', 'desktop_modern'), ('desktop_traditional', 'desktop_traditional'), ('tablet_standard', 'tablet_standard'), ('tablet_modern', 'tablet_modern'), ('tablet_traditional', 'tablet_traditional'), ('smartfon_standard', 'smartfon_standard'), ('smartfon_modern', 'smartfon_modern'), ('smartfon_traditional', 'smartfon_traditional')], default='auto', max_length=32, verbose_name='Gui type for pc web browser')),
                ('smartfon_gui_type', models.CharField(choices=[('auto', 'auto'), ('desktop_standard', 'desktop_standard'), ('desktop_modern', 'desktop_modern'), ('desktop_traditional', 'desktop_traditional'), ('tablet_standard', 'tablet_standard'), ('tablet_modern', 'tablet_modern'), ('tablet_traditional', 'tablet_traditional'), ('smartfon_standard', 'smartfon_standard'), ('smartfon_modern', 'smartfon_modern'), ('smartfon_traditional', 'smartfon_traditional')], default='auto', max_length=32, verbose_name='Gui type for smartfon')),
                ('tablet_gui_type', models.CharField(choices=[('auto', 'auto'), ('desktop_standard', 'desktop_standard'), ('desktop_modern', 'desktop_modern'), ('desktop_traditional', 'desktop_traditional'), ('tablet_standard', 'tablet_standard'), ('tablet_modern', 'tablet_modern'), ('tablet_traditional', 'tablet_traditional'), ('smartfon_standard', 'smartfon_standard'), ('smartfon_modern', 'smartfon_modern'), ('smartfon_traditional', 'smartfon_traditional')], default='auto', max_length=32, verbose_name='Gui type for tablet')),
                ('user_param', models.TextField(blank=True, null=True, verbose_name='User parameter')),
                ('custom_tags', models.TextField(blank=True, null=True, verbose_name='Custom tags')),
            ],
            options={
                'verbose_name_plural': 'SChAppSet',
                'verbose_name': 'SChAppSet',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('verbose_name', models.CharField(max_length=255, verbose_name='Verbose name')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChApp', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'SChChoice',
                'verbose_name': 'SChChoice',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChChoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChChoice', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'SChChoiceItem',
                'verbose_name': 'SChChoiceItem',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('AutoField', 'AutoField'), ('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('CommaSeparatedIntegerField', 'CommaSeparatedIntegerField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('FilePathField', 'FilePathField'), ('FloatField', 'FloatField'), ('ImageField', 'ImageField'), ('IntegerField', 'IntegerField'), ('IPAddressField', 'IPAddressField'), ('NullBooleanField', 'NullBooleanField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'), ('SlugField', 'SlugField'), ('SmallIntegerField', 'SmallIntegerField'), ('TextField', 'TextField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('XMLField', 'XMLField'), ('ForeignKey', 'ForeignKey'), ('GForeignKey', 'GenericForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('GManyToManyField', 'GenericManyToManyField'), ('HiddenForeignKey', 'HiddenForeignKey'), ('GHiddenForeignKey', 'GenericHiddenForeignKey'), ('UserField', 'UserField'), ('ForeignKeyWidthIcon', 'ForeignKeyWidthIcon'), ('ManyToManyFieldWidthIcon', 'ManyToManyFieldWidthIcon'), ('AutocompleteTextField', 'AutocompleteTextField'), ('ForeignKeyExt', 'ForeignKeyExt'), ('TreeForeignKey', 'TreeForeignKey'), ('GTreeForeignKey', 'GTreeForeignKey')], max_length=64, verbose_name='Type')),
                ('null', models.BooleanField(default=False, verbose_name='Null')),
                ('blank', models.BooleanField(default=False, verbose_name='Blank')),
                ('editable', models.BooleanField(default=False, verbose_name='Editable')),
                ('unique', models.BooleanField(default=False, verbose_name='Unique')),
                ('db_index', models.BooleanField(default=False, verbose_name='DB index')),
                ('default', models.CharField(blank=True, max_length=255, null=True, verbose_name='Default')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Help text')),
                ('choices', models.CharField(blank=True, max_length=255, null=True, verbose_name='Choices')),
                ('rel_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relation to')),
                ('param', models.CharField(blank=True, max_length=255, null=True, verbose_name='Param')),
                ('url_params', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url params')),
            ],
            options={
                'verbose_name_plural': 'SChField',
                'verbose_name': 'SChField',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('f', 'TemplateFilters'), ('t', 'TemplateTags'), ('c', 'Custom file'), ('m', 'Management command')], max_length=3, verbose_name='File  type')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('content', models.TextField(blank=True, editable=False, null=True, verbose_name='Content')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChApp', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'SChFiles',
                'verbose_name': 'SChFiles',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('module', models.CharField(blank=True, max_length=64, null=True, verbose_name='Module')),
                ('process_code', models.TextField(blank=True, null=True, verbose_name='Process code')),
                ('end_class_code', models.TextField(blank=True, null=True, verbose_name='End class code')),
                ('end_code', models.TextField(blank=True, null=True, verbose_name='End code')),
                ('doc', models.TextField(blank=True, null=True, verbose_name='Doc')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChApp', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Form',
                'verbose_name': 'Form',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('type', models.CharField(choices=[('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('ChoiceField', 'ChoiceField'), ('TypedChoiceField', 'TypedChoiceField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('FilePathField', 'FilePathField'), ('FloatField', 'FloatField'), ('ImageField', 'ImageField'), ('IntegerField', 'IntegerField'), ('IPAddressField', 'IPAddressField'), ('GenericIPAddressField', 'GenericIPAddressField'), ('MultipleChoiceField', 'MultipleChoiceField'), ('TypedMultipleChoiceField', 'TypedMultipleChoiceField'), ('NullBooleanField', 'NullBooleanField'), ('RegexField', 'RegexField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('UserField', 'UserField')], max_length=64, verbose_name='Type')),
                ('required', models.NullBooleanField(verbose_name='Required')),
                ('label', models.CharField(max_length=64, verbose_name='Label')),
                ('initial', models.CharField(blank=True, max_length=256, null=True, verbose_name='Initial')),
                ('widget', models.CharField(blank=True, max_length=64, null=True, verbose_name='Widget')),
                ('help_text', models.CharField(blank=True, max_length=256, null=True, verbose_name='Help text')),
                ('error_messages', models.CharField(blank=True, max_length=64, null=True, verbose_name='Error messages')),
                ('param', models.CharField(blank=True, max_length=64, null=True, verbose_name='Param')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChForm', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Form field',
                'verbose_name': 'Form field',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'css'), ('J', 'javascript'), ('P', 'python to javascript'), ('R', 'riot.js module'), ('I', 'icss to css')], max_length=1, verbose_name='Type')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('code', models.TextField(blank=True, editable=False, null=True, verbose_name='Code')),
                ('doc', models.TextField(blank=True, editable=False, null=True, verbose_name='Doc')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChAppSet', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Static files',
                'verbose_name': 'Static file',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_table', models.CharField(blank=True, max_length=255, null=True, verbose_name='Base table')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('verbose_name', models.CharField(max_length=255, verbose_name='Verbose name')),
                ('verbose_name_plural', models.CharField(max_length=255, verbose_name='Verbose name plural')),
                ('metaclass_code', models.TextField(blank=True, editable=False, null=True, verbose_name='Metaclass code')),
                ('table_code', models.TextField(blank=True, editable=False, null=True, verbose_name='Table code')),
                ('ordering', models.CharField(blank=True, default="['id']", max_length=255, null=True, verbose_name='Ordering')),
                ('doc', models.TextField(blank=True, editable=False, null=True, verbose_name='Doc')),
                ('generic', models.BooleanField(default=False, verbose_name='Generic')),
                ('url_params', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url params')),
                ('proxy_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proxy model')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChApp', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'SChTable',
                'verbose_name': 'SChTable',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Code')),
                ('doc', models.TextField(blank=True, null=True, verbose_name='Doc')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChApp', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'SChTask',
                'verbose_name': 'SChTask',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('direct_to_template', models.NullBooleanField(verbose_name='Direct to template')),
                ('url', models.CharField(blank=True, max_length=64, null=True, verbose_name='Url')),
                ('url_parm', models.CharField(blank=True, max_length=128, null=True, verbose_name='Parameters passed to the template')),
                ('template_code', models.TextField(blank=True, editable=False, null=True, verbose_name='Template code')),
                ('tags_mount', models.CharField(blank=True, max_length=256, null=True, verbose_name='Mount riot tags')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChApp', verbose_name='Parent')),
                ('static_files', models.ManyToManyField(blank=True, null=True, to='schbuilder.SChStatic', verbose_name='Static files')),
            ],
            options={
                'verbose_name_plural': 'SChTemplate',
                'verbose_name': 'SChTemplate',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SChView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('view_type', models.CharField(choices=[('t', 'Table action'), ('r', 'Row action'), ('u', 'View')], max_length=1, verbose_name='View type')),
                ('param', models.CharField(blank=True, max_length=255, null=True, verbose_name='Param')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('view_code', models.TextField(blank=True, editable=False, null=True, verbose_name='View code')),
                ('doc', models.TextField(blank=True, editable=False, null=True, verbose_name='Doc')),
                ('url_params', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url params')),
                ('ret_type', models.CharField(choices=[('T', 'Template'), ('O', 'Odf'), ('P', 'Pdf'), ('J', 'Json'), ('X', 'Xml'), ('U', 'User defined')], default='U', max_length=1, verbose_name='Return value type')),
                ('parent', schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChApp', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'SChView',
                'verbose_name': 'SChView',
                'default_permissions': ('add', 'change', 'delete', 'list'),
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='schfield',
            name='parent',
            field=schlib.schdjangoext.fields.HiddenForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChTable', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='schapp',
            name='parent',
            field=schlib.schdjangoext.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schbuilder.SChAppSet', verbose_name='Parent'),
        ),
    ]
