#!/usr/bin/env python

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

try:
    from pytigon_run import run
except:
    from pytigon.pytigon_run import run

if __name__ == "__main__":
    run()
