_("Target")
_("Number")
_("Description")
_("Date")
_("Update report")
_("New doc line")
_("order")
_("description")
_("amount")
_("element")
_("level")
_("Account operation")
_("Account state")
_("New account")
_("Classifier")
_("New document register")
_("name")
_("Register")
_("Name")
_("Status")
_("New element")
_("Order")
_("Discard:")
_("Discard status:")
_("(Are you sure you want to accept the document)? <br>")
_("(You accept the status): {{ action_name }}")
_("(Are you sure you want to discard the document)? <br>")
_("(You discard the status): {{ action_name }}")
