_("New project")
_("Import")
_("Import from git")
_("Restart server")
_("Update system projects from git")
_("Name")
_("Title")
_("Version")
_("Icon")
_("Select application!")
_("A Message Box")
_("Applications")
_("Table")
_("Choices")
_("Views")
_("Forms")
_("Menu")
_("Tasks")
_("Channel consumers")
_("Templates")
_("Other files")
_("Model extensions")
_("View extensions")
_("Url extensions")
_("Task extensions")
_("Channel consumer extensions")
_("Doc")
_("&New view")
_("View type")
_("Url")
_("Parameters")
_("Asynchronous")
_("New choice")
_("Choice list")
_("New item")
_("Value")
_("Table field list")
_("New template")
_("Url paramaters")
_("Direct to template")
_("File type")
_("New menu item")
_("New wiki item")
_("Permission")
_("Menu item list")
_("Tables")
_("New table")
_("Base table")
_("Proxy")
_("Generic")
_("Verbose name")
_("Table list")
_("Type")
_("Refresh")
_("Fields")
_("Description")
_("Connected to")
_("Null")
_("Blank")
_("Editable")
_("Unique")
_("Open in toolbar")
_("New application")
_("Module title")
_("Permissions")
_("Applications list")
_("New file")
_("New directory")
_("View")
_("Edit")
_("Rename")
_("Copy")
_("Move")
_("Delete")
_("Setup")
_("Help")
_("Notifications")
_("Install")
_("Run")
_("Import project")
_("New form")
_("Module")
_("New task")
_("Publish")
_("Published group")
_("Consumers")
_("&New consumer")
_("Search results")
_("Search")
_("Change password")
_("Logout")
_("Login")
_("New field")
_("Label")
_("Initial")
_("Widget")
_("Required")
_("Workflow type")
_("Creation date")
_("Acceptance date")
_("Email")
_("Item type")
_("Status")
_("New attachement")
_("Download")
_("Parameter type")
_("Parameter subtype")
_("Key")
_("Application")
_("Group")
_("Parent id")
_("Date")
_("Operator")
_("Operator id")
_("Sign in")
_("Wrong login or password, try again")
_("User name")
_("Password")
_("or sign in with")
_("I forgot my password")
_("Register")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("Cancel")
_("OK")
_("Field")
_("Delete the item")
_("Import data to table")
_("Action")
_("Download installer")
_("get row")
_("new row")
_("Whole Word")
_("Regular Expression")
_("New locale")
_("Sync translate messages")
_("Model base file")
_("View base file")
_("Url base file")
_("Task base file")
_("Channel consumer base file")
_("Build")
_("Application files")
_("Icon code")
_("New status")
_("Order")
_("Type 1")
_("Type 2")
_("Classifier 1")
_("Classifier 2")
_("Classifier 3")
_("Wiki pages")
_("New wiki page")
_("Modify or create a wiki object")
_("User defined blocks")
_("Subject")
_("Wiki name")
_("Manage")
_("Choice action")
_("Translation")
_("Success")
_("A restart signal has been sent, depending on the configuration, the restart may take from a few seconds to several hours")
_("Warning")
_("It is not possible to send a signal for restart")
_("Make migrations")
_("Make all migrations")
_("Migrate")
_("Create auto user")
_("Compile messages")
_("Qinfo")
_("Send mails")
_("{{field.description}}")
_("Common Groups")
_("New")
_("Update")
_("name")
_("description")
_("Report type")
_("group")
_("permission")
_("Owner")
_("Config")
_("User type")
_("Allowed document registers")
_("Allowed document types")
_("Allowed accounts")
_("New account operation")
_("Payment")
_("Account state")
_("Sign")
_("Amount")
_("Account")
_("Subcode")
_("Account name")
_("Target")
_("Period")
_("debit")
_("credit")
_("element")
_("classifier1value")
_("classifier2value")
_("classifier3value")
_("Data")
_("Classifier")
_("Are you sure you want to accept the document")
_("You accept the status")
_("Document type")
_("Correction")
_("Are you sure you want to discard the document")
_("You discard the status")
_("New document register")
_("New document:")
_("Number")
_("Back to status:")
_("Discard status:")
_("New element")
_("Code")
_("New document item")
_("order")
_("amount")
_("level")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("This is the title.")
_("This is full line translated text")
_("Serial number")
_("IP")
_("Active")
_("New tag")
_("Tag")
_("New group")
_("Main parameter")
_("Release date")
_("Artist")
_("Genre")
_("release_date")
_("artist")
_("genre")
_("Parent")
_("Param")
