_("New application set")
_("Import")
_("Restart server")
_("Select application!")
_("A Message Box")
_("Applications")
_("Table")
_("Choices")
_("Views")
_("Templates")
_("Menu")
_("Urls")
_("User Models")
_("User View")
_("User Url")
_("Forms")
_("Doc")
_("Tables")
_("New table")
_("Table list")
_("New choice")
_("Name")
_("Description")
_("Choice list")
_("New view")
_("New template")
_("New menu item")
_("New wiki item")
_("Menu item list")
_("Tasks")
_("Custom files")
_("User Tasks")
_("Fields")
_("Update server from git")
_("&New view")
_("Open in toolbar")
_("New application")
_("New locale")
_("Sync translate messages")
_("New form")
_("New task")
_("New item")
_("Table field list")
_("New field")
_("Install")
_("New url")
_("Import project")
_("Subject")
_("Wiki name")
_("Manage")
_("Choice action")
_("Download installer")
_("Consumers")
_("User Consumers")
_("&New consumer")
