_("Element")
_("Type")
_("New label type")
_("Name")
_("Title")
_("Item")
_("Group")
_("Update")
_("Common Groups")
_("New")
_("Owner")
_("Config")
_("User type")
_("Allowed document registers")
_("Allowed document types")
_("Allowed accounts")
_("name")
_("description")
_("Report type")
_("Date")
_("New status")
_("Order")
_("Description")
_("New document register")
_("Operator")
_("Data")
_("Account state")
_("Refresh account states")
_("Account name")
_("Period")
_("debit")
_("credit")
_("balance")
_("New account operation")
_("Name of payment")
_("Sign")
_("Quantity")
_("Document type")
_("Correction")
_("Are you sure you want to accept the document")
_("You accept the status")
_("Are you sure you want to discard the document")
_("You discard the status")
_("Application")
_("Declaration")
_("Template source")
_("Template")
_("Convert fields to html")
_("Save function")
_("Load function")
_("Object to str function")
_("Action template")
_("Info template")
_("New document item")
_("order")
_("item")
_("quantity")
_("Classifier")
_("New element")
_("Code")
_("Type 1")
_("Type 2")
_("Classifier 1")
_("Classifier 2")
_("Classifier 3")
_("New document:")
_("Register")
_("Target")
_("Number")
_("Status")
_("Back to status:")
_("Discard status:")
