_("Common Groups")
_("New")
_("Update")
_("name")
_("description")
_("Report type")
_("Date")
_("group")
_("permission")
_("Owner")
_("Config")
_("User type")
_("Allowed document registers")
_("Allowed document types")
_("Allowed accounts")
_("New account operation")
_("Description")
_("Payment")
_("Account state")
_("Sign")
_("Amount")
_("Account")
_("Subcode")
_("Account name")
_("Target")
_("Period")
_("debit")
_("credit")
_("element")
_("classifier1value")
_("classifier2value")
_("classifier3value")
_("Name")
_("Operator")
_("Data")
_("Type 1")
_("Type 2")
_("Classifier 1")
_("Classifier 2")
_("Classifier 3")
_("Classifier")
_("Are you sure you want to accept the document")
_("You accept the status")
_("Document type")
_("Correction")
_("Are you sure you want to discard the document")
_("You discard the status")
_("New document register")
_("New document:")
_("Register")
_("Number")
_("Status")
_("Back to status:")
_("Discard status:")
_("New element")
_("Type")
_("Code")
_("New status")
_("Order")
_("New document item")
_("order")
_("amount")
_("level")
