_("New file")
_("New directory")
_("View")
_("Edit")
_("Rename")
_("Copy")
_("Move")
_("Delete")
_("Setup")
_("Help")
_("New comment")
_("Comment")
_("Sender")
_("Recipient")
_("Workflow type")
_("Creation date")
_("Acceptance date")
_("Email")
_("Title")
_("Item type")
_("Status")
_("Name")
_("New attachement")
_("Download")
_("Parameter type")
_("Parameter subtype")
_("Key")
_("Value")
_("Type")
_("Label")
_("Application")
_("Table")
_("Group")
_("Parent id")
_("Date")
_("Description")
_("Operator")
_("Operator id")
_("Start date")
_("Deadline")
_("Email - action owner")
_("Email - action done")
_("Email - deadline exceeded")
_("Additional info")
_("Language code")
_("Time")
_("Item description")
_("Accept")
_("Reject")
_("ext")
_("Workflow items")
