_("New comment")
_("Language code")
_("Description")
_("New attachement")
_("Name")
_("ext")
_("Workflow items")
_("Preview")
_("Download")
_("New file")
_("New directory")
_("View")
_("Edit")
_("Rename")
_("Copy")
_("Move")
_("Delete")
_("Setup")
_("Help")
_("Application")
_("Table")
_("Group")
_("Parent id")
_("Date")
_("Operator")
_("Operator id")
_("Type")
_("Start date")
_("Deadline")
_("Email - action owner")
_("Email - action done")
_("Email - deadline exceeded")
_("Additional info")
_("New workflow type")
_("Script for new item")
_("Script for accept item")
_("Script for reject item")
_("Script for refresh queue")
_("Script for handle refresh event")
_("Regenerate workflow")
_("Workflow type")
_("Creation date")
_("Acceptance date")
_("Email")
_("Title")
_("Item description")
_("Status")
_("Accept")
_("Reject")
_("Comment")
_("Sender")
_("Recipient")
_("Time")
_("Parameter type")
_("Parameter subtype")
_("Key")
_("Value")
_("Label")
