APPS = [
    "schcontrols_demo",
    "schcomponents_demo",
    "tables_demo",
    "tables_adv_demo",
    "views_demo",
    "forms_demo",
    "templates_demo",
    "tasks_demo",
    "channels_demo",
    "wiki_demo",
    "commander_demo",
    "simplescripts_demo",
    "log_demo",
    "desktop_demo",
    "interfaces",
    "_schwiki.schwiki",
    "_schtools.schsimplescripts",
    "_schtools.schlog",
    "_schtools.schcommander",
    "_schtools.schtools",
    "_schtools.schattachements",
    "_schtools.schworkflow",
    "_schdata.schdoc",
    "_schdata.schelements",
    "_schcomponents.standard_components",
    "_schdata.schprofile",
    "_schsetup.schadmin",
    "_schtools.schtasks",
    "_schtools.schactions",
]
APPS_EXT = []
PUBLIC = True
MAIN_PRJ = False
