APPS = [
    "schsimplecontrolsdemo",
    "schcomponents",
    "schhtmllib",
    "schtabledemo",
    "schfilemanagerdemo",
    "schcommandshelldemo",
    "schspreadsheetdemo",
    "schtasksdemo",
    "schadvcontrolsdemo",
    "tables",
    "tables_adv",
    "views",
    "forms2",
    "templates",
    "tasks",
    "channels_demo",
    "wiki",
    "elements",
    "reports",
    "commander",
    "simplescripts",
    "attachements",
    "log",
    "desktop",
    "_schwiki.schwiki",
    "_schtools.schtasks",
    "_schtools.schcommander",
    "_schtools.schtools",
    "_schdata.schreports",
    "_schdata.schelements",
    "schcomponents.standard_components",
]
APPS_EXT = []
PUBLIC = True
MAIN_PRJ = False
