_("Serial number")
_("Description")
_("IP")
_("Active")
_("Key")
_("New group")
_("Main parameter")
_("Parameters")
_("User name")
_("Email")
_("New tag")
_("Tag")
_("Application")
_("Table")
_("Release date")
_("Artist")
_("Genre")
_("release_date")
_("artist")
_("description")
_("genre")
_("Parent")
_("Name")
_("Param")
_("This is the title.")
_("This is full line translated text")
