_("Description")
_("Serial number")
_("Description")
_("IP")
_("Active")
_("Key")
_("New group")
_("Main parameter")
_("Parameters")
_("User name")
_("Email")
_("New tag")
_("Tag")
_("Application")
_("Table")
_("Release date")
_("Artist")
_("Genre")
_("release_date")
_("artist")
_("description")
_("genre")
_("Parent")
_("Name")
_("Param")
_("This is the title.")
_("This is full line translated text")
_("Search results")
_("Search")
_("Change password")
_("Manage")
_("Logout")
_("Login")
_("Wiki pages")
_("New wiki page")
_("Regenerate workflow")
_("Workflow type")
_("Creation date")
_("Acceptance date")
_("Title")
_("Item description")
_("Status")
_("Download")
_("Accept")
_("Reject")
_("Message")
_("Edit page")
_("Edit page source")
_("This page do not exists yet!")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("New workflow type")
_("Workflow items")
_("Script for new item")
_("Script for accept item")
_("Script for reject item")
_("Script for refresh queue")
_("Script for handle refresh event")
_("get row")
_("new row")
