_("User name")
_("Email")
_("This is the title.")
_("This is full line translated text")
_("Serial number")
_("Description")
_("IP")
_("Active")
_("Key")
_("New tag")
_("Tag")
_("Application")
_("Table")
_("New group")
_("Main parameter")
_("Parameters")
_("release_date")
_("artist")
_("description")
_("genre")
_("Release date")
_("Artist")
_("Change password")
_("Setup")
_("Logout")
_("Login")
_("get row")
_("new row")
_("Edit page")
_("Edit page source")
_("This page do not exists yet!")
_("Modify or create a wiki object")
_("New wiki class")
_("Wiki pages")
_("New wiki page")
_("name")
_("New")
_("Report type")
_("Date")
_("Update")
_("Genre")
_("Parent")
_("Name")
_("Account state")
_("Account")
_("Subcode")
_("Account name")
_("Target")
_("Period")
_("debit")
_("credit")
_("element")
_("classifier1value")
_("classifier2value")
_("classifier3value")
_("New account operation")
_("Payment")
_("Sign")
_("Amount")
_("Param")
_("Search results")
_("Search")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("Report from publication")
_("User defined blocks")
_("New document item")
_("order")
_("amount")
_("level")
_("New status")
_("Order")
_("New demo document:")
_("New demo document item")
_("New document:")
_("Register")
_("Number")
_("Status")
_("Back to status:")
_("Discard status:")
_("New document register")
_("Document type")
_("Correction")
_("New element")
_("Type")
_("Code")
_("Sign in")
_("Wrong login or password, try again")
_("Password")
_("or sign in with")
_("I forgot my password")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("Cancel")
_("OK")
_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Import data to table")
_("Action")
_("Type 1")
_("Type 2")
_("Classifier 1")
_("Classifier 2")
_("Classifier 3")
