_("Download installer")
_("New project")
_("Import")
_("Import from git")
_("Restart server")
_("Update system projects from git")
_("Name")
_("Title")
_("Version")
_("Icon")
_("Select application!")
_("A Message Box")
_("Applications")
_("Table")
_("Choices")
_("Views")
_("Forms")
_("Menu")
_("Tasks")
_("Channel consumers")
_("Templates")
_("Other files")
_("Model extensions")
_("View extensions")
_("Url extensions")
_("Task extensions")
_("Channel consumer extensions")
_("Doc")
_("&New view")
_("View type")
_("Url")
_("Parameters")
_("Asynchronous")
_("New form")
_("Module")
_("Table list")
_("lp = os.path.dirname(os.path.abspath(__file__))")
_("rp = os.environ['PYTIGON_ROOT_PATH']")
_("Tables")
_("New table")
_("Base table")
_("Proxy")
_("Generic")
_("Verbose name")
_("Fields")
_("Description")
_("Type")
_("Connected to")
_("Null")
_("Blank")
_("Editable")
_("Unique")
_("Table field list")
_("New template")
_("Url paramaters")
_("Direct to template")
_("Open in toolbar")
_("New application")
_("Module title")
_("Permissions")
_("Applications list")
_("Sign in")
_("Wrong login or password, try again")
_("User name")
_("Password")
_("or sign in with")
_("I forgot my password")
_("Register")
_("Change Password")
_("Current Password")
_("New Password")
_("Confirm Password")
_("Cancel")
_("OK")
_("Field")
_("Value")
_("Delete the item")
_("Refresh")
_("Import data to table")
_("Action")
_("New choice")
_("Choice list")
_("File type")
_("Install")
_("Notifications")
_("Subject")
_("Wiki name")
_("Manage")
_("Choice action")
_("Run")
_("New item")
_("Translation")
_("Status")
_("New field")
_("Label")
_("Initial")
_("Widget")
_("Required")
_("Import project")
_("New menu item")
_("New wiki item")
_("Permission")
_("Menu item list")
_("Success")
_("A restart signal has been sent, depending on the configuration, the restart may take from a few seconds to several hours")
_("Warning")
_("It is not possible to send a signal for restart")
_("New url")
_("New locale")
_("Sync translate messages")
_("New task")
_("Publish")
_("Published group")
_("Consumers")
_("&New consumer")
_("Make migrations")
_("Make all migrations")
_("Migrate")
_("Create auto user")
_("Compile messages")
_("Qinfo")
_("Send mails")
_("{{field.description}}")
_("Logout")
_("Change password")
_("Setup")
_("Login")
_("New file")
_("New directory")
_("View")
_("Edit")
_("Rename")
_("Copy")
_("Move")
_("Delete")
_("Help")
