_("New project")
_("Import")
_("Import from git")
_("Restart server")
_("Update system projects from git")
_("Name")
_("Title")
_("Version")
_("Icon")
_("Select application!")
_("A Message Box")
_("Applications")
_("Table")
_("Choices")
_("Views")
_("Forms")
_("Menu")
_("Tasks")
_("Channel consumers")
_("Templates")
_("Other files")
_("Model extensions")
_("View extensions")
_("Url extensions")
_("Task extensions")
_("Channel consumer extensions")
_("Doc")
_("&New view")
_("View type")
_("Url")
_("Parameters")
_("Asynchronous")
_("New choice")
_("Choice list")
_("New item")
_("Value")
_("Table field list")
_("New template")
_("Url paramaters")
_("Direct to template")
_("File type")
_("New menu item")
_("New wiki item")
_("Permission")
_("Menu item list")
_("Tables")
_("New table")
_("Base table")
_("Proxy")
_("Generic")
_("Verbose name")
_("Table list")
_("Type")
