_("Wiki pages")
_("New wiki page")
_("Edit page")
_("Edit wiki page")
_("Edit ihtml page")
_("Edit html page")
_("Edit page source")
_("New wiki class")
_("New wiki object")
_("monaco.Range(pos.lineNumber, 1, pos.lineNumber, 1")
_("Modify or create a wiki object")
_("Publis")
_("Wiki subject")
_("backup_copies")
_("Group of rigths to view")
_("Group of rigths to edit")
_("Report from publication")
_("(This page don't exists yet!)")
_("(This page do not exists yet!)")
