_("Modify or create a wiki object")
_("User defined blocks")
_("Wiki pages")
_("New wiki page")
_("New wiki class")
_("Wiki subject")
_("Group of rigths to view")
_("Group of rigths to edit")
_("backup_copies")
_("Report from publication")
_("Edit page")
_("Edit page source")
_("This page do not exists yet!")
